services:
  mysql:
    image: 'mysql:9.4.0'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
    ports:
      - '3306:3306'
    volumes:
      - ./db_schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
