name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: 21

jobs:

  Build:
    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    steps:

      - uses: actions/checkout@v4

      - run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE test;' -uroot -proot

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - run: ./gradlew clean ktlintCheck assemble test war --stacktrace

      - run: ./gradlew wrapper --gradle-version latest --stacktrace

      - uses: stefanzweifel/git-auto-commit-action@v5
