name: ci

on: [ push ]

env:
  JAVA_VERSION: 21

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew clean ktlintFormat assemble test jar --stacktrace

      - run: ./gradlew wrapper --gradle-version latest --stacktrace
      - run: ./gradlew wrapper --gradle-version latest --stacktrace

      - uses: stefanzweifel/git-auto-commit-action@v5
