name: ci

on: [ push ]

env:
  JAVA_VERSION: 21

jobs:

  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew wrapper --gradle-version latest --stacktrace
      - run: ./gradlew wrapper --gradle-version latest --stacktrace
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update Gradle wrapper

      - run: ./gradlew clean ktlintFormat assemble test jar --stacktrace
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Ktlint format
